In [1]:
import numpy as np

In [65]:
intarr=np.arange(9).reshape((3,3))
fltarr=np.array([[1.0,2.0,3.0],[4.5,5.5,6.5],[7.9,8.9,9.9]])
strarr=np.array([['a','b','c'],['d','e','f'],['x','y','z']])
cplxarr=np.random.random(9) + np.random.random(9) * 1j
cplxarr=cplxarr.reshape((3,3))

In [66]:
intarr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
fltarr


array([[1. , 2. , 3. ],
       [4.5, 5.5, 6.5],
       [7.9, 8.9, 9.9]])

In [68]:
strarr

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['x', 'y', 'z']], dtype='<U1')

In [69]:
cplxarr

array([[0.35213258+0.4342785j , 0.86780563+0.52698796j,
        0.01448612+0.39303041j],
       [0.2697472 +0.77167727j, 0.75088293+0.81659832j,
        0.14498482+0.27766029j],
       [0.69606415+0.74280067j, 0.15910074+0.61579794j,
        0.90344494+0.48133751j]])

In [70]:
intarr.shape

(3, 3)

In [71]:
fltarr.shape

(3, 3)

In [72]:
strarr.shape

(3, 3)

In [73]:
cplxarr.shape


(3, 3)

In [74]:
addmat=intarr+fltarr
print(addmat)

[[ 1.   3.   5. ]
 [ 7.5  9.5 11.5]
 [13.9 15.9 17.9]]


In [75]:
fltarr.transpose()

array([[1. , 4.5, 7.9],
       [2. , 5.5, 8.9],
       [3. , 6.5, 9.9]])

In [76]:
print('dot product of intarr and fltarr')
print(np.dot(intarr,fltarr))

dot product of intarr and fltarr
[[ 20.3  23.3  26.3]
 [ 60.5  72.5  84.5]
 [100.7 121.7 142.7]]


In [77]:
print('elementwise product of intarr and fltarr')
print(np.multiply(intarr,fltarr))

elementwise product of intarr and fltarr
[[ 0.   2.   6. ]
 [13.5 22.  32.5]
 [47.4 62.3 79.2]]


In [78]:
print('accessing diagnol of matrix')
for i in range(len(intarr)):
  print(intarr[i][i])

accessing diagnol of matrix
0
4
8


In [79]:
newlist=[1,2,3,4,5,6,7,8,9]
print('accessing first 4 elements of array',newlist[:4])


accessing first 4 elements of array [1, 2, 3, 4]


In [80]:
print('reverse list',newlist[::-1])


reverse list [9, 8, 7, 6, 5, 4, 3, 2, 1]


In [84]:
import pandas as pd
data=pd.read_csv('https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2019-financial-year-provisional/Download-data/annual-enterprise-survey-2019-financial-year-provisional-csv.csv')

In [85]:
data.head()

Year  ...                             Industry_code_ANZSIC06
0  2019  ...  ANZSIC06 divisions A-S (excluding classes K633...
1  2019  ...  ANZSIC06 divisions A-S (excluding classes K633...
2  2019  ...  ANZSIC06 divisions A-S (excluding classes K633...
3  2019  ...  ANZSIC06 divisions A-S (excluding classes K633...
4  2019  ...  ANZSIC06 divisions A-S (excluding classes K633...

[5 rows x 10 columns]

In [87]:
convertednp=data['Year'].to_numpy()

In [88]:
print(convertednp)

[2019 2019 2019 ... 2013 2013 2013]


In [89]:
convertednp.shape

(32445,)