<a href="https://colab.research.google.com/github/adityav1810/Semester_5_Labs/blob/master/ECSE303L-AIandML/Lab10/Task_1_Software_cost_estimation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objective: Feature Subset Selection to Improve Software Cost Estimation

## Dataset
This is a PROMISE Software Engineering Repository data set made publicly available to encourage repeatable, verifiable, refutable, and/or improvable predictive models of software engineering. The main objective is to estimate the software cost estimation using feature subset selection techniques.

## Attributes
1.	RELY {Nominal,Very_High,High,Low} 
2.	DATA {High,Low,Nominal,Very_High} 
3.	CPLX {Very_High,High,Nominal,Extra_High,Low} 
4.	TIME {Nominal,Very_High,High,Extra_High} 
5.	STOR {Nominal,Very_High,High,Extra_High} 
6.	VIRT {Low,Nominal,High}
7.	TURN {Nominal,High,Low}
8.	ACAP {High,Very_High,Nominal} 
9.	AEXP {Nominal,Very_High,High} 
10.	PCAP {Very_High,High,Nominal}
11.	VEXP {Low,Nominal,High}
12.	LEXP {Nominal,High,Very_Low,Low} 
13.	MODP {High,Nominal,Very_High,Low}
14.	TOOL {Nominal,High,Very_High,Very_Low,Low} 
15.	SCED {Low,Nominal,High}
16.	LOC numeric 

## Target Class
ACT_EFFORT numeric %17

### Source: http://promise.site.uottawa.ca/SERepository/datasets/cocomonasa_v1.arff

Tasks:
1.	Obtain the software cost estimation dataset
2.	Apply pre-processing techniques (if any)
3.	Apply feature subset selection techniques such as correlation analysis, forward selection, backward elimination, recursive feature elimination etc. Find best possible subset of features from each method.
4.	Divide dataset into training and testing set, respectively.
5.	Implement support vector regression (SVR), Linear regression, and Decision tree.
6.	Ensemble SVR, Linear regression and Decision tree. 
7.	Evaluate Coefficient of determination and Root mean square error for all the models including the ensemble one.
8.	Conclude the results

Helpful links: https://scikit-learn.org/stable/modules/ensemble.html
https://www.analyticsvidhya.com/blog/2020/03/support-vector-regression-tutorial-for-machine-learning/
https://medium.com/pursuitnotes/support-vector-regression-in-6-steps-with-python-c4569acd062d
https://scikit-learn.org/stable/auto_examples/svm/plot_svm_regression.html


## Task 1: Implementation of regression models 

In [1]:
# Load the libraries
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import sklearn
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2, f_regression
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import math
from sklearn import tree
from sklearn.datasets import make_friedman1
from sklearn.ensemble import GradientBoostingRegressor

In [13]:
fl = open("/content/week12lab1.txt","r") 
k=0
for i in fl.readlines():
    if(k==0):
        dat=[x.strip() for x in i[:-22].split(',')]
        data=np.array(dat)
    k=1
    temp=[x.strip() for x in i[:-22].split(',')]
    temp=np.array(temp)
    data = np.vstack ((data, temp) )
    print([x.strip() for x in i[:-22].split(',')])
    

['Nominal', 'High', 'Very_High', 'Nominal', 'Nominal', 'Low', 'Nominal', 'High', 'Nominal', 'Very_High', 'Low', 'Nominal', 'High', 'Nominal', 'Low', '70', '278']
['Very_High', 'High', 'High', 'Very_High', 'Very_High', 'Nominal', 'Nominal', 'Very_High', 'Very_High', 'Very_High', 'Nominal', 'High', 'High', 'High', 'Low', '227', '1181']
['Nominal', 'High', 'High', 'Very_High', 'High', 'Low', 'High', 'High', 'Nominal', 'High', 'Low', 'High', 'High', 'Nominal', 'Low', '177.9', '1248']
['High', 'Low', 'High', 'Nominal', 'Nominal', 'Low', 'Low', 'Nominal', 'Nominal', 'Nominal', 'Nominal', 'High', 'High', 'Nominal', 'Low', '115.8', '480']
['High', 'Low', 'High', 'Nominal', 'Nominal', 'Low', 'Low', 'Nominal', 'Nominal', 'Nominal', 'Nominal', 'High', 'High', 'Nominal', 'Low', '29.5', '120']
['High', 'Low', 'High', 'Nominal', 'Nominal', 'Low', 'Low', 'Nominal', 'Nominal', 'Nominal', 'Nominal', 'High', 'High', 'Nominal', 'Low', '19.7', '60']
['High', 'Low', 'High', 'Nominal', 'Nominal', 'Low', 'Lo

In [3]:
# Preprocessing
# Encoding categorical variables (if any)
# Feature Scaling
# Filling missing values (if any)
data=data.astype("str")
#print(data.shape)
y=data[:,16].astype("f")
x=data[:,:16].astype("str")
#print(x)


label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(x[:,0])
#print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
X = onehot_encoder.fit_transform(integer_encoded)


    
for i in range(1,x.shape[1]-1):
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(x[:,i])
    #print(integer_encoded)

    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    X=np.column_stack((X,onehot_encoded))

X=np.column_stack((X,x[:,15]))
#X=np.append(X,x[:,15],axis=1)
#print(X.shape)
#print(y.shape)
#print(X)
#print(y)

X[:,55] = preprocessing.normalize(X[:,55].reshape(1,-1))
#X = preprocessing.normalize(X)
print(X)
print(X.shape)


[['0.0' '0.0' '1.0' ... '1.0' '0.0' '0.07395893633170382']
 ['0.0' '0.0' '1.0' ... '1.0' '0.0' '0.07395893633170382']
 ['0.0' '0.0' '0.0' ... '1.0' '0.0' '0.23983826496138239']
 ...
 ['0.0' '0.0' '1.0' ... '0.0' '0.0' '0.08241138619818425']
 ['0.0' '0.0' '1.0' ... '0.0' '0.0' '0.012044741059734623']
 ['0.0' '0.0' '1.0' ... '0.0' '0.0' '0.020391535302884053']]
(61, 56)


In [4]:
# Apply feature subset selection techniques 
X = SelectKBest(f_regression, k=56).fit_transform(X.astype("f"), y)
print(X.shape)

(61, 56)


In [5]:
# Divide the dataset to training and testing set
X_train, X_test, y_train, y_test = train_test_split(X.astype("f"), y, test_size=0.33, random_state=42)

print(X)
print(y)

[[0.         0.         1.         ... 1.         0.         0.07395893]
 [0.         0.         1.         ... 1.         0.         0.07395893]
 [0.         0.         0.         ... 1.         0.         0.23983827]
 ...
 [0.         0.         1.         ... 0.         0.         0.08241139]
 [0.         0.         1.         ... 0.         0.         0.01204474]
 [0.         0.         1.         ... 0.         0.         0.02039154]]
[ 278.   278.  1181.  1248.   480.   120.    60.   300.    18.    50.
   60.   114.    42.    60.    42.   450.    90.   210.    48.   815.
  239.   170.    62.    70.    82.   192.   117.6  117.6   31.2   25.2
    8.4   10.8   36.   352.8  324.   360.   215.   360.    48.    60.
   60.    24.    36.    72.    48.    72.  2400.  3240.  2120.   370.
  750.   420.   252.   107.  2300.   400.   973.  1368.   571.4   98.8
  155. ]


In [9]:
# Build regression models 
regr = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.2))
regr.fit(X_train, y_train)
y_pred=regr.predict(X_test)
mse = sklearn.metrics.mean_squared_error(y_test, y_pred)
rmse = math.sqrt(mse)
print("Root Mean Squared Error Support Vector Machine: ",rmse)
print()
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)
y_pred = regr.predict(X_test)
mse = sklearn.metrics.mean_squared_error(y_test, y_pred)
rmse = math.sqrt(mse)
print("Root Mean Squared Error Linear Regression: ",rmse)


clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
mse = sklearn.metrics.mean_squared_error(y_test, y_pred)
rmse = math.sqrt(mse)
print("Root Mean Squared Error Decision Tree: ",rmse)


Root Mean Squared Error Support Vector Machine:  561.043882552876

Root Mean Squared Error Linear Regression:  291.52793873400884
Root Mean Squared Error Decision Tree:  330.2590930033951


##Task 2: Ensemble regression models


In [10]:
# Ensemble the regression models
est = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1,max_depth=1, random_state=0, loss='ls').fit(X_train, y_train)
print('GradientBoostingRegressor MSE : ',mean_squared_error(y_test, est.predict(X_test)))


GradientBoostingRegressor MSE :  93540.30280587511
